/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  anon_sym_LBRACK = 2,
  anon_sym_RBRACK = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_let = 7,
  anon_sym_EQ = 8,
  anon_sym_SEMI = 9,
  anon_sym_for = 10,
  anon_sym_in = 11,
  anon_sym_while = 12,
  anon_sym_DOT_DOT = 13,
  anon_sym_use = 14,
  anon_sym_COLON_COLON = 15,
  anon_sym_fn = 16,
  aux_sym_binary_expr_token1 = 17,
  anon_sym_LBRACE = 18,
  anon_sym_RBRACE = 19,
  sym_number = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_identifier = 23,
  sym_string = 24,
  sym_source_file = 25,
  sym_statement = 26,
  sym_attribute = 27,
  sym_attribute_item = 28,
  sym_let_statement = 29,
  sym_for_loop = 30,
  sym_while_loop = 31,
  sym_range_expr = 32,
  sym_import = 33,
  sym_path = 34,
  sym_function_decl = 35,
  sym_function_call = 36,
  sym_binary_expr = 37,
  sym_expression = 38,
  sym_block = 39,
  sym_boolean = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_attribute_item_repeat1 = 42,
  aux_sym_path_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_let] = "keyword",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_for] = "keyword",
  [anon_sym_in] = "keyword",
  [anon_sym_while] = "keyword",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_use] = "use",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_fn] = "keyword",
  [aux_sym_binary_expr_token1] = "binary_expr_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_attribute] = "attribute",
  [sym_attribute_item] = "attribute_item",
  [sym_let_statement] = "let_statement",
  [sym_for_loop] = "for_loop",
  [sym_while_loop] = "while_loop",
  [sym_range_expr] = "range_expr",
  [sym_import] = "import",
  [sym_path] = "path",
  [sym_function_decl] = "function_decl",
  [sym_function_call] = "function_call",
  [sym_binary_expr] = "binary_expr",
  [sym_expression] = "expression",
  [sym_block] = "block",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_attribute_item_repeat1] = "attribute_item_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_for] = anon_sym_let,
  [anon_sym_in] = anon_sym_let,
  [anon_sym_while] = anon_sym_let,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_fn] = anon_sym_let,
  [aux_sym_binary_expr_token1] = aux_sym_binary_expr_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_attribute] = sym_attribute,
  [sym_attribute_item] = sym_attribute_item,
  [sym_let_statement] = sym_let_statement,
  [sym_for_loop] = sym_for_loop,
  [sym_while_loop] = sym_while_loop,
  [sym_range_expr] = sym_range_expr,
  [sym_import] = sym_import,
  [sym_path] = sym_path,
  [sym_function_decl] = sym_function_decl,
  [sym_function_call] = sym_function_call,
  [sym_binary_expr] = sym_binary_expr,
  [sym_expression] = sym_expression,
  [sym_block] = sym_block,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_attribute_item_repeat1] = aux_sym_attribute_item_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_binary_expr_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_item] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_while_loop] = {
    .visible = true,
    .named = true,
  },
  [sym_range_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_function_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_end = 2,
  field_fn_kw = 3,
  field_for_kw = 4,
  field_in_kw = 5,
  field_let_kw = 6,
  field_name = 7,
  field_range = 8,
  field_start = 9,
  field_variable = 10,
  field_while_kw = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_end] = "end",
  [field_fn_kw] = "fn_kw",
  [field_for_kw] = "for_kw",
  [field_in_kw] = "in_kw",
  [field_let_kw] = "let_kw",
  [field_name] = "name",
  [field_range] = "range",
  [field_start] = "start",
  [field_variable] = "variable",
  [field_while_kw] = "while_kw",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 4},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_while_kw, 0},
  [2] =
    {field_for_kw, 0},
    {field_in_kw, 2},
    {field_range, 3},
    {field_variable, 1},
  [6] =
    {field_let_kw, 0},
  [7] =
    {field_fn_kw, 0},
  [8] =
    {field_args, 2},
    {field_name, 0},
  [10] =
    {field_end, 2},
    {field_start, 0},
  [12] =
    {field_args, 2},
    {field_args, 3},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 2,
        '#', 25,
        '(', 28,
        ')', 30,
        ',', 29,
        '.', 4,
        ':', 5,
        ';', 35,
        '=', 34,
        '[', 26,
        ']', 27,
        'f', 6,
        'i', 16,
        'l', 7,
        't', 17,
        'u', 19,
        'w', 12,
        '{', 49,
        '}', 50,
        '!', 48,
        '<', 48,
        '>', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(30);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 't') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(74);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(45);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '#', 25,
        ')', 30,
        ';', 35,
        '=', 48,
        'f', 66,
        'l', 57,
        'u', 69,
        'w', 62,
        '{', 49,
        '}', 50,
        '!', 48,
        '<', 48,
        '>', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_for);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_while);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_binary_expr_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_binary_expr_token1);
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 23},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 23},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 23},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 23},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 23},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 23},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 23},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [aux_sym_binary_expr_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(51),
    [sym_statement] = STATE(3),
    [sym_attribute] = STATE(9),
    [sym_let_statement] = STATE(9),
    [sym_for_loop] = STATE(9),
    [sym_while_loop] = STATE(9),
    [sym_import] = STATE(9),
    [sym_function_decl] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_for] = ACTIONS(9),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_use] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(24), 1,
      anon_sym_let,
    ACTIONS(27), 1,
      anon_sym_for,
    ACTIONS(30), 1,
      anon_sym_while,
    ACTIONS(33), 1,
      anon_sym_use,
    ACTIONS(36), 1,
      anon_sym_fn,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(9), 7,
      sym_attribute,
      sym_let_statement,
      sym_for_loop,
      sym_while_loop,
      sym_import,
      sym_function_decl,
      sym_function_call,
  [39] = 10,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_for,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_use,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(2), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(9), 7,
      sym_attribute,
      sym_let_statement,
      sym_for_loop,
      sym_while_loop,
      sym_import,
      sym_function_decl,
      sym_function_call,
  [77] = 10,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_for,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_use,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(5), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(9), 7,
      sym_attribute,
      sym_let_statement,
      sym_for_loop,
      sym_while_loop,
      sym_import,
      sym_function_decl,
      sym_function_call,
  [115] = 10,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_for,
    ACTIONS(11), 1,
      anon_sym_while,
    ACTIONS(13), 1,
      anon_sym_use,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(2), 2,
      sym_statement,
      aux_sym_source_file_repeat1,
    STATE(9), 7,
      sym_attribute,
      sym_let_statement,
      sym_for_loop,
      sym_while_loop,
      sym_import,
      sym_function_decl,
      sym_function_call,
  [153] = 2,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(50), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [167] = 2,
    ACTIONS(52), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(54), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [181] = 6,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(35), 1,
      sym_expression,
    ACTIONS(58), 2,
      sym_number,
      sym_string,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym_binary_expr,
      sym_boolean,
  [203] = 2,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(66), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [217] = 2,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(70), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [231] = 6,
    ACTIONS(62), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_expression,
    ACTIONS(58), 2,
      sym_number,
      sym_string,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym_binary_expr,
      sym_boolean,
  [253] = 2,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(76), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [267] = 2,
    ACTIONS(78), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(80), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [281] = 2,
    ACTIONS(82), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(84), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [295] = 2,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(88), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [309] = 2,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(92), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [323] = 2,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(96), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [337] = 2,
    ACTIONS(98), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(100), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [351] = 2,
    ACTIONS(102), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(104), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [365] = 2,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_RBRACE,
    ACTIONS(108), 6,
      anon_sym_let,
      anon_sym_for,
      anon_sym_while,
      anon_sym_use,
      anon_sym_fn,
      sym_identifier,
  [379] = 5,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(38), 1,
      sym_expression,
    ACTIONS(58), 2,
      sym_number,
      sym_string,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym_binary_expr,
      sym_boolean,
  [398] = 5,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(26), 1,
      sym_expression,
    ACTIONS(58), 2,
      sym_number,
      sym_string,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym_binary_expr,
      sym_boolean,
  [417] = 5,
    ACTIONS(62), 1,
      sym_identifier,
    STATE(29), 1,
      sym_expression,
    ACTIONS(58), 2,
      sym_number,
      sym_string,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym_binary_expr,
      sym_boolean,
  [436] = 1,
    ACTIONS(110), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym_binary_expr_token1,
      anon_sym_LBRACE,
  [443] = 1,
    ACTIONS(112), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym_binary_expr_token1,
      anon_sym_LBRACE,
  [450] = 1,
    ACTIONS(114), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      aux_sym_binary_expr_token1,
      anon_sym_LBRACE,
  [457] = 3,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(118), 1,
      anon_sym_COLON_COLON,
    STATE(28), 1,
      aux_sym_path_repeat1,
  [467] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_COLON_COLON,
    STATE(28), 1,
      aux_sym_path_repeat1,
  [477] = 3,
    ACTIONS(125), 1,
      aux_sym_binary_expr_token1,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_block,
  [487] = 3,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_attribute_item_repeat1,
  [497] = 3,
    ACTIONS(118), 1,
      anon_sym_COLON_COLON,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    STATE(27), 1,
      aux_sym_path_repeat1,
  [507] = 3,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      aux_sym_attribute_item_repeat1,
  [517] = 3,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym_attribute_item_repeat1,
  [527] = 2,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 1,
      sym_identifier,
  [534] = 2,
    ACTIONS(125), 1,
      aux_sym_binary_expr_token1,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
  [541] = 2,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
  [548] = 1,
    ACTIONS(120), 2,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
  [553] = 2,
    ACTIONS(125), 1,
      aux_sym_binary_expr_token1,
    ACTIONS(152), 1,
      anon_sym_SEMI,
  [560] = 2,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_block,
  [567] = 2,
    ACTIONS(125), 1,
      aux_sym_binary_expr_token1,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
  [574] = 2,
    ACTIONS(156), 1,
      sym_identifier,
    STATE(49), 1,
      sym_path,
  [581] = 2,
    ACTIONS(158), 1,
      sym_number,
    STATE(7), 1,
      sym_range_expr,
  [588] = 2,
    ACTIONS(160), 1,
      sym_identifier,
    STATE(50), 1,
      sym_attribute_item,
  [595] = 2,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
  [602] = 1,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [607] = 1,
    ACTIONS(162), 1,
      anon_sym_DOT_DOT,
  [611] = 1,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
  [615] = 1,
    ACTIONS(166), 1,
      sym_identifier,
  [619] = 1,
    ACTIONS(168), 1,
      anon_sym_SEMI,
  [623] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
  [627] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
  [631] = 1,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
  [635] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [639] = 1,
    ACTIONS(178), 1,
      anon_sym_SEMI,
  [643] = 1,
    ACTIONS(180), 1,
      anon_sym_EQ,
  [647] = 1,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
  [651] = 1,
    ACTIONS(184), 1,
      sym_number,
  [655] = 1,
    ACTIONS(186), 1,
      sym_identifier,
  [659] = 1,
    ACTIONS(188), 1,
      sym_identifier,
  [663] = 1,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
  [667] = 1,
    ACTIONS(192), 1,
      anon_sym_LBRACK,
  [671] = 1,
    ACTIONS(194), 1,
      anon_sym_in,
  [675] = 1,
    ACTIONS(196), 1,
      sym_identifier,
  [679] = 1,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
  [683] = 1,
    ACTIONS(200), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 153,
  [SMALL_STATE(7)] = 167,
  [SMALL_STATE(8)] = 181,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 217,
  [SMALL_STATE(11)] = 231,
  [SMALL_STATE(12)] = 253,
  [SMALL_STATE(13)] = 267,
  [SMALL_STATE(14)] = 281,
  [SMALL_STATE(15)] = 295,
  [SMALL_STATE(16)] = 309,
  [SMALL_STATE(17)] = 323,
  [SMALL_STATE(18)] = 337,
  [SMALL_STATE(19)] = 351,
  [SMALL_STATE(20)] = 365,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 398,
  [SMALL_STATE(23)] = 417,
  [SMALL_STATE(24)] = 436,
  [SMALL_STATE(25)] = 443,
  [SMALL_STATE(26)] = 450,
  [SMALL_STATE(27)] = 457,
  [SMALL_STATE(28)] = 467,
  [SMALL_STATE(29)] = 477,
  [SMALL_STATE(30)] = 487,
  [SMALL_STATE(31)] = 497,
  [SMALL_STATE(32)] = 507,
  [SMALL_STATE(33)] = 517,
  [SMALL_STATE(34)] = 527,
  [SMALL_STATE(35)] = 534,
  [SMALL_STATE(36)] = 541,
  [SMALL_STATE(37)] = 548,
  [SMALL_STATE(38)] = 553,
  [SMALL_STATE(39)] = 560,
  [SMALL_STATE(40)] = 567,
  [SMALL_STATE(41)] = 574,
  [SMALL_STATE(42)] = 581,
  [SMALL_STATE(43)] = 588,
  [SMALL_STATE(44)] = 595,
  [SMALL_STATE(45)] = 602,
  [SMALL_STATE(46)] = 607,
  [SMALL_STATE(47)] = 611,
  [SMALL_STATE(48)] = 615,
  [SMALL_STATE(49)] = 619,
  [SMALL_STATE(50)] = 623,
  [SMALL_STATE(51)] = 627,
  [SMALL_STATE(52)] = 631,
  [SMALL_STATE(53)] = 635,
  [SMALL_STATE(54)] = 639,
  [SMALL_STATE(55)] = 643,
  [SMALL_STATE(56)] = 647,
  [SMALL_STATE(57)] = 651,
  [SMALL_STATE(58)] = 655,
  [SMALL_STATE(59)] = 659,
  [SMALL_STATE(60)] = 663,
  [SMALL_STATE(61)] = 667,
  [SMALL_STATE(62)] = 671,
  [SMALL_STATE(63)] = 675,
  [SMALL_STATE(64)] = 679,
  [SMALL_STATE(65)] = 683,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 5, 0, 5),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 5, 0, 5),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_loop, 4, 0, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_loop, 4, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_loop, 3, 0, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_loop, 3, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_decl, 6, 0, 5),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_decl, 6, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_expr, 3, 0, 7),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_expr, 3, 0, 7),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 4),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attribute_item_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attribute_item_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_item, 1, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [172] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_item, 3, 0, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_item, 4, 0, 6),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_item, 5, 0, 8),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kurai(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kurai",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 3,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
